//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Consultorio_Medico.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConsultaMedica
    {
        public int Id { get; set; }
        public int Id_Medico { get; set; }
        public int Id_Historico { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public string Estudios { get; set; }
        public Nullable<System.DateTime> FechaProxConsulta { get; set; }
        public string Sintomas { get; set; }
        public string Diagnostico { get; set; }
        public string MedicacionSugerida { get; set; }
        public string Observaciones { get; set; }
        public string Notas { get; set; }
        public string EstudiosSolicitados { get; set; }
        public string EstudiosResibidos { get; set; }
        public string ResultadosEstudiosResibidos { get; set; }
    
        public virtual HistorialConsultas HistorialConsultas { get; set; }
        public virtual Medicos Medicos { get; set; }

        public bool Save(ConsultaMedica consultaMedica)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                db.ConsultaMedica.Add(consultaMedica);

                if (db.SaveChanges() == 1)
                {
                    return true;
                }

                return false;
            }
        }

        public IEnumerable<dynamic> GetTunosPendientes(int idMedico)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                return (from t in db.Turnos
                       join p in db.Pacientes on t.Id_Paciente equals p.Id
                       join h in db.HistorialConsultas on p.Id equals h.Id_Paciente
                       join c in db.ConsultaMedica on h.Id equals c.Id_Historico
                       join m in db.Medicos on c.Id_Medico equals m.Id
                       join mc in db.MedicoConsultorio on m.Id equals mc.Id_Medico
                       where c.Estado == "Pendiente" && (DateTime.Now.Hour >= mc.H_Entrada.Hours && DateTime.Now.Hour <= mc.H_Salida.Hours) && m.Id == idMedico
                       select new { p.Nombre, p.Apellido, p.DNI, c.Estado, c.Id }).ToList();
            }
        }

    }
}
