//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Consultorio_Medico.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MedicoConsultorio
    {
        public int Id { get; set; }
        public int Id_Medico { get; set; }
        public int Id_Consultorio { get; set; }
        public System.TimeSpan H_Entrada { get; set; }
        public System.TimeSpan H_Salida { get; set; }
        public Nullable<bool> Lunes { get; set; }
        public Nullable<bool> Martes { get; set; }
        public Nullable<bool> Miercoles { get; set; }
        public Nullable<bool> Jueves { get; set; }
        public Nullable<bool> Viernes { get; set; }
        public Nullable<bool> Sabado { get; set; }
        public Nullable<bool> Domingo { get; set; }

        public virtual Consultorios Consultorios { get; set; }
        public virtual Medicos Medicos { get; set; }

        public bool Save(MedicoConsultorio medicoConsultorio)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                db.MedicoConsultorio.Add(medicoConsultorio);

                if (db.SaveChanges() == 1)
                {
                    return true;
                }
                return false;
            }
        }

        public ICollection<MedicoConsultorio> GetByConsultorio(int idConsultorio)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                return db.MedicoConsultorio.Where(x => x.Id_Consultorio == idConsultorio).ToList();
            }
        }

        public ICollection<MedicoConsultorio> GetByMedico(int idMedico)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                return db.MedicoConsultorio.Where(x => x.Id_Medico == idMedico).ToList();
            }
        }
    }
}
