//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Consultorio_Medico.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MedicoEspecialidad
    {
        public int Id { get; set; }
        public int Id_Medico { get; set; }
        public int Id_Especialidad { get; set; }

        public virtual Especialidades Especialidades { get; set; }
        public virtual Medicos Medicos { get; set; }

        public bool Save(MedicoEspecialidad medicoEspecialidad)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                db.MedicoEspecialidad.Add(medicoEspecialidad);

                if (db.SaveChanges() == 1)
                {
                    return true;
                }
                return false;
            }
        }

        public ICollection<MedicoEspecialidad> GetByMedico(int id)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                return db.MedicoEspecialidad.Include("Especialidades").Where(x => x.Id_Medico == id).ToList();
            }
        }

        public ICollection<MedicoEspecialidad> GeyByEspecialidad(int id)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                return db.MedicoEspecialidad.Include("Medicos").Where(x => x.Id_Especialidad == id).ToList();
            }
        }
    }
}
