//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Consultorio_Medico.Modelo
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class Turnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turnos()
        {
            this.ConsultaMedica = new HashSet<ConsultaMedica>();
        }
    
        public int Id { get; set; }
        public int Id_Paciente { get; set; }
        public int Id_Consultorio { get; set; }
    
        public virtual Consultorios Consultorios { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaMedica> ConsultaMedica { get; set; }

        public bool Save(Turnos turno)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                db.Turnos.Add(turno);

                if (db.SaveChanges() == 1)
                {
                    return true;
                }
                return false;
            }
        }

        public Turnos GetTurnoById(int id)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                return db.Turnos.Where(x => x.Id_Paciente == id).FirstOrDefault();
            }
        }

        public int GetCantidadTurnos(int idMedico)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                return (from t in db.Turnos
                       join c in db.ConsultaMedica on t.Id equals c.Id_Turno
                       join m in db.Medicos on c.Id_Medico equals m.Id
                       where DateTime.Today == c.Fecha && m.Id == idMedico
                       select t).Count();
            }
        }
    }
}
