//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Consultorio_Medico.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnos
    {
        public int Id { get; set; }
        public int Id_Paciente { get; set; }
        public int Id_Consultorio { get; set; }
    
        public virtual Consultorios Consultorios { get; set; }
        public virtual Pacientes Pacientes { get; set; }

        public bool Save(Turnos turno)
        {
            using (Proyecto_centro_medicoEntities db = new Proyecto_centro_medicoEntities())
            {
                db.Turnos.Add(turno);

                if (db.SaveChanges() == 1)
                {
                    return true;
                }
                return false;
            }
        }
    }
}
